# Generated by Django 4.2.4 on 2023-08-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='customer_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
